//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlaceMVC.Models
{



    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using MarketPlaceMVC.Models;

    [MetadataType(typeof(UserProfileMetadata))]

    public partial class tblUser
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string Password { get; set; }

        public string ConfirmPassword { get; set; }
        public Nullable<int> credential_ID { get; set; }
        public byte[] userimg { get; set; }
    }
}
